// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MultivariableCalculus")>]
[<assembly: AssemblyProductAttribute("MultivariableCalculus")>]
[<assembly: AssemblyDescriptionAttribute("MultivariableCalculus")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MultivariableCalculus"
    let [<Literal>] AssemblyProduct = "MultivariableCalculus"
    let [<Literal>] AssemblyDescription = "MultivariableCalculus"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
